
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.print.*;
import java.text.*;
import javax.swing.JTable;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ranggga
 */
public class cetaklaporan extends javax.swing.JFrame {

    /**
     * Creates new form cetaklaporan
     */
    public cetaklaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Cetak Laporan");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(101, 82, 56));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\picture\\wheels 2.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Speedy Speed Boy");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rent Car");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 120));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Kembali Ke Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, -1, 40));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Cari Transaksi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton3.setText("Cetak Laporan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 110, 30));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomer Sewa", "Tanggal Sewa", "Tanggal Kembali", "ID Mobil", "Plat Nomer", "Nama Mobil", "ID Penyewa", "Nama Penyewa", "Alamat", "Nomer Hp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 820, 110));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Cari transaksi sewa berdasarkan Nomer Sewa");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 90, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("Tampil Laporan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        carinosewa();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       cetaklaporan();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        tampillaporan();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cetaklaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cetaklaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cetaklaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cetaklaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cetaklaporan().setVisible(true);
            }
        });
    }
    
    private void carinosewa()
    {
          String idm, platno, namambl;
        String nos, tgls, tglk, idmb,idpn;      
        String idp,namap,alamatp,nohp_p;
        try{
            String idpecarian=jTextField1.getText();
           Object[] row={"Nomer Sewa","Tanggal Sewa","Tanggal Kembali","ID Mobil","Plat Nomer","Nama Mobil"
                    ,"ID Penyewa","Nama Penyewa","Alamat","Nomer HP"};
            DefaultTableModel tabmodel;
            tabmodel = new DefaultTableModel(null, row);
            jTable3.setModel(tabmodel);
            Class.forName("java.sql.Driver");
            String db="jdbc:mysql://localhost/rentalmobil";
            String user="root";
            String pass="";
            Connection con=DriverManager.getConnection(db,user,pass);
            String quer="SELECT sewa.no_sewa , sewa.tgl_sewa, sewa.tgl_kembali,mobil.id_mobil"
                    + ",mobil.plat_no, mobil.nama_mobil ,penyewa.id_penyewa,penyewa.nama_penyewa"
                    + ", penyewa.alamat, penyewa.nohp "
                    + "FROM sewa "
                    + "INNER JOIN mobil ON(sewa.id_mobil=mobil.id_mobil )"
                    + "INNER JOIN penyewa ON(sewa.id_penyewa=penyewa.id_penyewa)"
                    +"where no_sewa= '"+idpecarian+"'";
            Statement st=con.createStatement();
            ResultSet rs= st.executeQuery(quer);
                if(rs.next())
            {
                nos=rs.getString("no_sewa");
                tgls=rs.getString("tgl_sewa");
                tglk=rs.getString("tgl_kembali");
                idmb=rs.getString("id_mobil");
                platno=rs.getString("plat_no");
                namambl=rs.getString("nama_mobil");
                idpn=rs.getString("id_penyewa");
                namap=rs.getString("nama_penyewa");
                alamatp=rs.getString("alamat");
                nohp_p=rs.getString("nohp");
                String data[]={nos,tgls,tglk,idmb,platno,namambl,idpn,namap,alamatp,nohp_p};    
                tabmodel.addRow(data);
            }
               else
                {
                    JOptionPane.showMessageDialog(null,"Data Yang Dicari Tidak Dapat Ditemukan ");
                }
        }
        catch(Exception a){
           JOptionPane.showMessageDialog(null,"Tidak Dapat Ditemukan "+a);}
    }
    
    private void cetaklaporan()
    {
        MessageFormat header = new MessageFormat("Laporan Detail Transaksi Sewa Pinjam");
        MessageFormat footer = new MessageFormat("Halaman  {0,number,integer}"); 
        try
        {
            jTable3.print(JTable.PrintMode.NORMAL, header, footer);
        }catch(java.awt.print.PrinterException e)
        {
            //System.err.println("Tidak Dapat mencetak");
            JOptionPane.showMessageDialog(null,"Tidak Dapat mencetak "+ e);
        }
    }
    
    private void tampillaporan()
    {
        String idm, platno, namambl;
        String nos, tgls, tglk, idmb,idpn;      
        String idp,namap,alamatp,nohp_p;
         try
        {
            Object[] row={"Nomer Sewa","Tanggal Sewa","Tanggal Kembali","ID Mobil",
                "Plat Nomer","Nama Mobil"
                    ,"ID Penyewa","Nama Penyewa","Alamat","Nomer HP"};
            DefaultTableModel tabmodel;
            tabmodel = new DefaultTableModel(null, row);
            jTable3.setModel(tabmodel);
            Class.forName("java.sql.Driver");
            String db="jdbc:mysql://localhost/rentalmobil";
            String user="root";
            String pass="";
            Connection con=DriverManager.getConnection(db,user,pass);
            String quer="SELECT sewa.no_sewa , sewa.tgl_sewa, sewa.tgl_kembali,mobil.id_mobil"
                    + ",mobil.plat_no, mobil.nama_mobil ,penyewa.id_penyewa,penyewa.nama_penyewa"
                    + ", penyewa.alamat, penyewa.nohp "
                    + "FROM sewa "
                    + "INNER JOIN mobil ON(sewa.id_mobil=mobil.id_mobil )"
                    + "INNER JOIN penyewa ON(sewa.id_penyewa=penyewa.id_penyewa)";
            Statement st=con.createStatement();
            ResultSet rs= st.executeQuery(quer);
            while(rs.next())
            {
                nos=rs.getString("no_sewa");
                tgls=rs.getString("tgl_sewa");
                tglk=rs.getString("tgl_kembali");
                idmb=rs.getString("id_mobil");
                platno=rs.getString("plat_no");
                namambl=rs.getString("nama_mobil");
                idpn=rs.getString("id_penyewa");
                namap=rs.getString("nama_penyewa");
                alamatp=rs.getString("alamat");
                nohp_p=rs.getString("nohp");
                String data[]={nos,tgls,tglk,idmb,platno,namambl,idpn,namap,alamatp,nohp_p};   
                tabmodel.addRow(data);
            }  
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null,"Tidak dapat menampilkan Data mobil "+ e);}   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
