
import com.mysql.cj.xdevapi.DatabaseObject;
import com.mysql.cj.xdevapi.DbDoc;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;  
import java.util.Properties;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ranggga
 */
public class formsewa extends javax.swing.JFrame {

    /**
     * Creates new form formsewa
     */
    public formsewa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Transaksi Sewa Pinjam");
        setMaximumSize(new java.awt.Dimension(890, 603));
        setMinimumSize(new java.awt.Dimension(890, 603));
        setPreferredSize(new java.awt.Dimension(1317, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(101, 82, 56));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 120));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Speedy Speed Boy");
        jLabel2.setToolTipText("");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 370, 50));

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rent Car");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 120));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("ID Mobil");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Nomer Sewa");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Status");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Nama Penyewa");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Nomer Hp");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Nama Mobil");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Plat Nomer Mobil");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 110, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 110, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 110, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 110, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 110, -1));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 110, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ready", "Sudah Disewa", "Maintenance" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton2.setText("Tampil Mobil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 20));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton3.setText("Tampil Penyewa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 280, -1, 30));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setText("Kembali Ke Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 500, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Mobil", "Plat Nomer", "Nama", "Merk", "Jenis", "CC", "Bahan Bakar", "Harga Sewa", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 700, 100));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Cari mobil yang akan disewa berdasarkan ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 160, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("ID Penyewa");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, -1, -1));

        jTextField8.setToolTipText("");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 110, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Tanggal Sewa");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Tanggal Kembali");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton6.setText("Cari Mobil");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Penyewa", "Nama", "Alamat", "Jenis Kelamin", "TTL", "Pekerjaan", "No HP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 520, 100));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Cari penyewa yang akan menyewa berdasarkan ID");
        jLabel15.setToolTipText("");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, -1, -1));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, 120, -1));

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton7.setText("Cari Penyewa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 280, -1, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomer Sewa", "Tanggal Sewa", "Tanggal Kembali", "ID Mobil", "ID Penyewa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 700, 110));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 110, -1));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 110, -1));

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton8.setText("Tampil");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton9.setText("Ganti Status Mobil");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    tampilmobilsewa();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    carimobildisewa();
    }//GEN-LAST:event_jButton6ActionPerformed
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel modl= (DefaultTableModel)jTable1.getModel();
        int selecttedrow = jTable1.getSelectedRow();
        jTextField4.setText(modl.getValueAt(selecttedrow, 0).toString());
        jTextField5.setText(modl.getValueAt(selecttedrow, 1).toString());
        jTextField6.setText(modl.getValueAt(selecttedrow, 2).toString());
        jComboBox1.setSelectedItem(modl.getValueAt(selecttedrow, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    tambahdaftarsewa();    
    }//GEN-LAST:event_jButton1ActionPerformed
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    caripenyewanya();
    }//GEN-LAST:event_jButton7ActionPerformed
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    tampilpenyewasewa();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modl= (DefaultTableModel)jTable2.getModel();
        int selecttedrow = jTable2.getSelectedRow();
        jTextField3.setText(modl.getValueAt(selecttedrow, 0).toString());
        jTextField8.setText(modl.getValueAt(selecttedrow, 1).toString());
        jTextField1.setText(modl.getValueAt(selecttedrow, 6).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        tampildaftarsewa();
    }//GEN-LAST:event_jButton8ActionPerformed
    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modl= (DefaultTableModel)jTable3.getModel();
        int selecttedrow = jTable3.getSelectedRow();
        jTextField2.setText(modl.getValueAt(selecttedrow, 0).toString());
        jTextField10.setText(modl.getValueAt(selecttedrow, 1).toString());
        jTextField11.setText(modl.getValueAt(selecttedrow, 2).toString());
        jTextField4.setText(modl.getValueAt(selecttedrow, 3).toString());
        jTextField3.setText(modl.getValueAt(selecttedrow, 4).toString());
    }//GEN-LAST:event_jTable3MouseClicked
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        hapusdaftarsewa();
    }//GEN-LAST:event_jButton4ActionPerformed
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       gantistatus();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formsewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formsewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formsewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formsewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formsewa().setVisible(true);
            }
        });
    }
    
    private void gantistatus()
    {
        String idmbl=jTextField4.getText();
         Object stats=jComboBox1.getSelectedItem();
       try
        {
            
            Class.forName("java.sql.Driver");
            String db="jdbc:mysql://localhost/rentalmobil";
            String user="root";
            String pass="";
            Connection con=DriverManager.getConnection(db,user,pass);
            Statement st=con.createStatement();
            String quer="update mobil set status='"+stats+"' where id_mobil='"+idmbl+"'";
                    //+" where id_mobil='"+idmbl+"'";
            st.executeUpdate(quer);
            JOptionPane.showMessageDialog(null, "Sukses Diganti");
        }
        catch(Exception a)
        {JOptionPane.showMessageDialog(null,"Error "+ a);}
    }
    
    private void hapusdaftarsewa()
    {
    int row=jTable3.getSelectedRow();
        String id=jTable3.getModel().getValueAt(row, 0).toString();
        String queriy="DELETE FROM sewa WHERE no_sewa = '"+id+"'";
        try {
            Class.forName("java.sql.Driver");
            String db="jdbc:mysql://localhost/rentalmobil";
            String user="root";
            String pass="";
            Connection con=DriverManager.getConnection(db,user,pass);       
            PreparedStatement pstmt = con.prepareStatement(queriy);
           pstmt.executeUpdate();
           JOptionPane.showMessageDialog(null, "Sukses Dihapus");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Tidak Dapat Di Hapus "+ e);
        }}
    
    
    private void tambahdaftarsewa()
    {
        String nsewa=jTextField2.getText();
        String tglsewa=jTextField10.getText();
        String tglkem=jTextField11.getText();
        String id_mb=jTextField4.getText();
        String platn=jTextField5.getText();
        String nmambl=jTextField6.getText();
        String id_p=jTextField3.getText();
        String nm_p=jTextField8.getText();
        String nohpp=jTextField1.getText();
        try
       {
            Class.forName("java.sql.Driver");
            String db="jdbc:mysql://localhost/rentalmobil";
            String user="root";
            String pass="";
            Connection con=DriverManager.getConnection(db,user,pass);
            Statement st=con.createStatement();
            String quer="insert into sewa(no_sewa,tgl_sewa,tgl_kembali,id_mobil,id_penyewa)"
                    + "values('"+nsewa+"','"+tglsewa+"','"+tglkem+"','"+id_mb+"','"+id_p+"');";
             st.executeUpdate(quer);
            JOptionPane.showMessageDialog(null, "Sukses Ditambahkan");
             jTextField2.setText(" ");
            jTextField10.setText(" ");
            jTextField11.setText(" ");
            jTextField4.setText(" ");
             jTextField3.setText(" ");
             jComboBox1.setSelectedItem("Ready");
             jTextField6.setText(" ");
             jTextField1.setText(" ");
             jTextField5.setText(" ");
             jTextField8.setText(" ");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(null," Error tidak dapat ditambahkan "+ e);}
    }
    
    private void tampildaftarsewa()
    {
       String nos, tgls, tglk, idmb,idpn;
         try
        {
             Object[] row={"Nomer Sewa","Tanggal Sewa","Tanggal Kembali",
                 "ID Mobil","ID Penyewa"};
            DefaultTableModel tabmodel;
            tabmodel = new DefaultTableModel(null, row);
            jTable3.setModel(tabmodel);
            Class.forName("java.sql.Driver");
            String db="jdbc:mysql://localhost/rentalmobil";
            String user="root";
            String pass="";
            Connection con=DriverManager.getConnection(db,user,pass);
        String quer="SELECT no_sewa , tgl_sewa,tgl_kembali,id_mobil"
                    + ",id_penyewa "
                + "FROM sewa ";
            Statement st=con.createStatement();
            ResultSet rs= st.executeQuery(quer);
            while(rs.next())
            {
                nos=rs.getString("no_sewa");
                tgls=rs.getString("tgl_sewa");
                tglk=rs.getString("tgl_kembali");
                idmb=rs.getString("id_mobil");
                idpn=rs.getString("id_penyewa");
                String data[]={nos,tgls,tglk,idmb,idpn};   
                tabmodel.addRow(data);
            }  
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null,"Tidak dapat menampilkan Data mobil "+ e);}  
    }
    
    private void tampilmobilsewa()
    {
    String idm, platno, namambl, merkk,jns,cc ,bb, hs,sts;    
         try
        {
            Object[] row={"ID Mobil","Plat Nomer","Nama","Merk","Jenis","CC",
                "Bahan Bakar"
            ,"Harga Sewa","Status"};
            DefaultTableModel tabmodel;
            tabmodel = new DefaultTableModel(null, row);
            jTable1.setModel(tabmodel);
            Class.forName("java.sql.Driver");
            String db="jdbc:mysql://localhost/rentalmobil";
            String user="root";
            String pass="";
            Connection con=DriverManager.getConnection(db,user,pass);
            String quer="SELECT id_mobil , plat_no , nama_mobil , merk , jenis ,"
                    + " cc , bahan_bakar , harga_sewa , status FROM mobil";
            Statement st=con.createStatement();
            ResultSet rs= st.executeQuery(quer);
            while(rs.next())
            {
                idm=rs.getString("id_mobil");
                platno=rs.getString("plat_no");
                namambl=rs.getString("nama_mobil");
                merkk=rs.getString("merk");
                jns=rs.getString("jenis");
                cc=rs.getString("cc");
                bb=rs.getString("bahan_bakar");
                hs=rs.getString("harga_sewa");
                sts=rs.getString("status");
                String data[]={idm,platno,namambl,merkk,jns,cc,bb,hs,sts};   
                tabmodel.addRow(data);
            }  
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null,"Tidak dapat menampilkan Data mobil "+ e);}
    }
    
    private void carimobildisewa()
    {
        String idm, platno, namambl, merkk,jns,cc ,bb, hs,sts;
        try{
            String idpecarian=jTextField7.getText();
            Object[] row={"ID Mobil","Plat Nomer","Nama","Merk","Jenis","CC","Bahan Bakar"
            ,"Harga Sewa","Status"};
            DefaultTableModel tabmodel;
            tabmodel = new DefaultTableModel(null, row);
            jTable1.setModel(tabmodel);
            Class.forName("java.sql.Driver");
            String db="jdbc:mysql://localhost/rentalmobil";
            String user="root";
            String pass="";
            Connection con=DriverManager.getConnection(db,user,pass);
            String quer="SELECT * FROM mobil where id_mobil = '"+idpecarian+"'";
            Statement st=con.createStatement();
            ResultSet rs= st.executeQuery(quer);
                if(rs.next())
            {
                idm=rs.getString("id_mobil");
                platno=rs.getString("plat_no");
                namambl=rs.getString("nama_mobil");
                merkk=rs.getString("merk");
                jns=rs.getString("jenis");
                cc=rs.getString("cc");
                bb=rs.getString("bahan_bakar");
                hs=rs.getString("harga_sewa");
                sts=rs.getString("status");
                String data[]={idm,platno,namambl,merkk,jns,cc,bb,hs,sts};   
                tabmodel.addRow(data);
            }
               else
                {
                    JOptionPane.showMessageDialog(null,"Data Tidak Dapat Ditemukans ");
                }
        }
        catch(Exception a){
           JOptionPane.showMessageDialog(null,"Tidak Dapat Ditemukans "+a);}
    }
    
    private void caripenyewanya()
    {
   String idp,namap,alamatp,jenisp,ttlp,pekerjaanp,nohp_p;
        try{
            String idpecarian=jTextField9.getText();
            Object[] row={"ID Penyewa","Nama","Alamat","Jenis Kelamin",
                "TTL","Pekerjaan","No HP"};
            DefaultTableModel tabmodel;
            tabmodel = new DefaultTableModel(null, row);
            jTable2.setModel(tabmodel);
            Class.forName("java.sql.Driver");
            String db="jdbc:mysql://localhost/rentalmobil";
            String user="root";
            String pass="";
            Connection con=DriverManager.getConnection(db,user,pass);
            String quer="SELECT * FROM penyewa where id_penyewa = '"+idpecarian+"'";
            Statement st=con.createStatement();
            ResultSet rs= st.executeQuery(quer);
                if(rs.next())
            {
                idp=rs.getString("id_penyewa");
                namap=rs.getString("nama_penyewa");
                alamatp=rs.getString("alamat");
                jenisp=rs.getString("jenis_kel");
                ttlp=rs.getString("ttl");
                pekerjaanp=rs.getString("pekerjaan");
                nohp_p=rs.getString("nohp");
               
                String data[]={idp,namap,alamatp,jenisp,ttlp,pekerjaanp,nohp_p};   
                tabmodel.addRow(data);
            }else
                {JOptionPane.showMessageDialog(null,"Tidak Dapat Ditemukans ");
                } 
        }
        catch(Exception a){
           JOptionPane.showMessageDialog(null,"Tidak Dapat Ditemukans "+a);}
    }

    private void tampilpenyewasewa()
    {
          String idp,namap,alamatp,jenisp,ttlp,pekerjaanp,nohp_p;
         try     
        {
            Object[] row = {"ID Penyewa", "Nama", "Alamat", "Jenis Kelamin", 
                "TTL", "Pekerjaan", "No HP"};
            DefaultTableModel tabmod;
            tabmod = new DefaultTableModel(null, row);
            jTable2.setModel(tabmod);
            Class.forName("java.sql.Driver");
            String db="jdbc:mysql://localhost/rentalmobil";
            String user="root";
            String pass="";
            Connection con=DriverManager.getConnection(db,user,pass);
             String quer="SELECT id_penyewa , nama_penyewa , alamat , "
                     + "jenis_kel , ttl , pekerjaan , nohp  FROM penyewa";
            Statement st=con.createStatement();       
            ResultSet rs= st.executeQuery(quer);
            while(rs.next())
            {
                idp=rs.getString("id_penyewa");
                namap=rs.getString("nama_penyewa");
                alamatp=rs.getString("alamat");
                jenisp=rs.getString("jenis_kel");
                ttlp=rs.getString("ttl");
                pekerjaanp=rs.getString("pekerjaan");
                nohp_p=rs.getString("nohp");
                String datt[]={idp,namap,alamatp,jenisp,ttlp,pekerjaanp,nohp_p};
                tabmod.addRow(datt);
            }
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null,"Can't Show Database "+ e);}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
